package com.qtrmoon.sysManage.bean;

import org.apache.struts.action.ActionForm;

/**
 * SysFunctionunit generated by MyEclipse - Hibernate Tools
 */

public class FunctionUnitForm extends ActionForm {

	// Fields
	private String id;//

	private String name;// 功能单元名称

	private String info;// 功能单元说明

	private Long ord;// 排序

	private String picIco;// 功能单元图标

	// Constructors

	/** default constructor */
	public FunctionUnitForm() {
	}

	/** minimal constructor */
	public FunctionUnitForm(String id) {
		this.id = id;
	}

	/** full constructor */
	public FunctionUnitForm(String id, String name, String info) {
		this.id = id;
		this.name = name;
		this.info = info;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Long getOrd() {
		return ord;
	}

	public void setOrd(Long ord) {
		this.ord = ord;
	}

	public String getPicIco() {
		return picIco;
	}

	public void setPicIco(String picIco) {
		this.picIco = picIco;
	}

}