package com.qtrmoon.sysManage.bean;

/**
 * SysFunction generated by MyEclipse - Hibernate Tools
 */

public class Function implements java.io.Serializable {

	// Fields

	private String id;

	private String name;// 功能名称

	private String pid;

	private String link;// 连接地址

	private String isShow;// 菜单/隐藏权限

	private String info;// 说明

	private String picIco;// 图标

	private String picImg;// 描述图片

	private Long ord;// 排序

	private String treeTrack;// 树结构路径

	private String moduleName;

	// Constructors

	/** default constructor */
	public Function() {
	}

	/** minimal constructor */
	public Function(String id) {
		this.id = id;
	}

	/** full constructor */
	public Function(String id, String name, String pid, String link,
			String isshow, String info, String picico, String picimg) {
		this.id = id;
		this.name = name;
		this.pid = pid;
		this.link = link;
		this.isShow = isshow;
		this.info = info;
		this.picIco = picico;
		this.picImg = picimg;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getIsShow() {
		return isShow;
	}

	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	public String getPicIco() {
		return picIco;
	}

	public void setPicIco(String picIco) {
		this.picIco = picIco;
	}

	public String getPicImg() {
		return picImg;
	}

	public void setPicImg(String picImg) {
		this.picImg = picImg;
	}

	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public Long getOrd() {
		return ord;
	}

	public void setOrd(Long ord) {
		this.ord = ord;
	}

	public String getTreeTrack() {
		return treeTrack;
	}

	public void setTreeTrack(String treeTrack) {
		this.treeTrack = treeTrack;
	}

	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

}