package com.qtrmoon.sysManage.bean;

import com.qtrmoon.toolkit.tree.TreeNode;

/**
 * SysFunction generated by MyEclipse - Hibernate Tools
 */

public class FunctionForm extends TreeNode {

	// Fields

	private String id;

	private String name;// 功能名称

	private String pid;

	private String link;// 连接地址

	private String isShow;// 1菜单/0隐藏权限

	private String info;// 说明

	private String picIco;// 图标

	private String picImg;// 描述图片

	private Long ord;// 排序

	private String treeTrack;// 树结构路径

	private String moduleName;// 模块名称

	// Constructors

	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/** default constructor */
	public FunctionForm() {
	}

	/** minimal constructor */
	public FunctionForm(String id) {
		this.id = id;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getIsShow() {
		return isShow;
	}

	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	public String getPicIco() {
		return picIco;
	}

	public void setPicIco(String picIco) {
		this.picIco = picIco;
	}

	public String getPicImg() {
		return picImg;
	}

	public void setPicImg(String picImg) {
		this.picImg = picImg;
	}

	public Long getOrd() {
		return ord;
	}

	public void setOrd(Long ord) {
		super.order = ord.intValue();
		this.ord = ord;
	}

	public String getTreeId() {
		return this.id;
	}

	public String getTreePId() {
		return this.pid;
	}

	public String getTreeTrack() {
		return treeTrack;
	}

	public void setTreeTrack(String treeTrack) {
		this.treeTrack = treeTrack;
	}

}