package com.qtrmoon.sysManage.bean;

import com.qtrmoon.toolkit.tree.TreeNode;

/**
 * SysOrgan generated by MyEclipse - Hibernate Tools
 */

public class OrganForm extends TreeNode {

	// Fields

	private String id;//

	private String pid;// 父Id

	private String name;// 机构名称

	private String isMaster;// 是否机构（0机构；1部门）

	private String info;// 说明

	private Long ord;// 排序

	private String treeTrack;// 树结构路径
	
	private String code; // 机构代码

	private String type;// 机构类型

	// Constructors

	/** default constructor */
	public OrganForm() {
	}

	/** minimal constructor */
	public OrganForm(String id) {
		this.id = id;
	}

	// Property accessors
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getIsMaster() {
		return isMaster;
	}

	public void setIsMaster(String isMaster) {
		this.isMaster = isMaster;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getTreeId() {
		return this.id;
	}

	public String getTreePId() {
		return this.pid;
	}

	public Long getOrd() {
		return ord;
	}

	public void setOrd(Long ord) {
		super.setOrder(ord.intValue());
		this.ord = ord;
	}

	public String getTreeTrack() {
		return treeTrack;
	}

	public void setTreeTrack(String treeTrack) {
		this.treeTrack = treeTrack;
	}
}