package com.qtrmoon.sysManage.bean;

/**
 * SysOrgan generated by MyEclipse - Hibernate Tools
 */

public class RoleFunction implements java.io.Serializable {

	// Fields

	private String id;//

	private String roleId;

	private String functionId;

	// Constructors

	/** default constructor */
	public RoleFunction() {
	}

	/** minimal constructor */
	public RoleFunction(String id) {
		this.id = id;
	}

	// Property accessors

	public String getFunctionId() {
		return functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}