package com.qtrmoon.sysManage.bean;

/**
 * SysOrgan generated by MyEclipse - Hibernate Tools
 */

public class RoleUser implements java.io.Serializable {

	// Fields

	private String id;//

	private String roleId;//

	private String userId;// 

	// Constructors

	/** default constructor */
	public RoleUser() {
	}

	/** minimal constructor */
	public RoleUser(String id) {
		this.id = id;
	}

	// Property accessors

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}