package com.qtrmoon.sysManage.bean;

/**
 * SysRole generated by MyEclipse - Hibernate Tools
 */

public class Role implements java.io.Serializable {

	// Fields

	private String id;//

	private String name;// 角色名称

	private String isLocal;// 是否全局角色（1全局，0局部）

	private String info;// 说明

	private Long ord;// 排序

	private String classify;// 类别
	
	private String organId;

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** minimal constructor */
	public Role(String id) {
		this.id = id;
	}

	/** full constructor */
	public Role(String id, String name, String islocal, String info) {
		this.id = id;
		this.name = name;
		this.isLocal = islocal;
		this.info = info;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getIsLocal() {
		return isLocal;
	}

	public void setIsLocal(String isLocal) {
		this.isLocal = isLocal;
	}

	public String getClassify() {
		return classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	public Long getOrd() {
		return ord;
	}

	public void setOrd(Long ord) {
		this.ord = ord;
	}

	public String getOrganId() {
		return organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}
}