package com.qtrmoon.sysManage.bean;

import java.util.Date;

/**
 * SysUser generated by MyEclipse - Hibernate Tools
 */

public class User implements java.io.Serializable {

	// Fields

	private String id;//

	private String loginName;// 登陆名

	private String password;// 密码

	private String userName;// 用户名字

	private String classify;// 类型

	private String state;// 状态

	private Date regTime;// 注册时间

	private String organId;

	// Constructors
	/** default constructor */
	public User() {
	}

	/** minimal constructor */
	public User(String id) {
		this.id = id;
	}

	/** full constructor */
	public User(String id, String loginname, String password, String username) {
		this.id = id;
		this.loginName = loginname;
		this.password = password;
		this.userName = username;
	}

	// Property accessors

	public String getClassify() {
		return classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	public Date getRegTime() {
		return regTime;
	}

	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getOrganId() {
		return organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

}